name: Deploy Python Function App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and zip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        zip -r deploy.zip . -x '.git/*' '.github/*' '*.md'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Function App
      run: |
        az functionapp deployment source config-zip \
          -g azuredocwrapper-gw_group \
          -n azuredocwrapper-gw \
          --src deploy.zip
